# MySQL 配置
[mysql]
host = 43.172.89.43
port = 3306
user = root
password = 5871258712
database = edu_rag

# Redis 配置
[redis]
host = 43.172.89.43
port = 6379
password = 5871258712
db = 0

# 日志配置
[logger]
log_file = logs/app.log